/**
 * Extended Coding Prompts Library - 200 Professional Prompts
 * Sources: GitHub best practices, Clean Code, OWASP, Design Patterns, etc.
 */

export interface ExtendedPrompt {
    promptId: string;
    title: string;
    prompt: string;
    category: string;
    tags: string[];
    source?: string;
}

// Categories: Implementation, Debugging, Refactoring, Testing, Documentation, 
// Algorithms, Database, Security, Architecture, DevOps, Frontend, Backend,
// Mobile, AI/ML, Code Review, Performance, API, Cloud, Microservices, TypeScript

export const EXTENDED_PROMPTS: ExtendedPrompt[] = [
    // ===== IMPLEMENTATION (20 prompts) =====
    { promptId: 'impl-01', title: 'Feature Implementation', prompt: 'I need to implement [feature] in [language]. Requirements:\n1. [Req 1]\n2. [Req 2]\nConsider: error handling, edge cases, performance, best practices.', category: 'Implementation', tags: ['feature'], source: 'Clean Code' },
    { promptId: 'impl-02', title: 'REST API Endpoint', prompt: 'Create a REST API endpoint for [resource] in [framework].\nMethod: [GET/POST/PUT/DELETE]\nRoute: /api/[path]\nInclude validation, error handling, TypeScript types.', category: 'Implementation', tags: ['api', 'rest'], source: 'RESTful API Design' },
    { promptId: 'impl-03', title: 'React Component', prompt: 'Create a React component for [purpose].\nProps: [list props with types]\nFeatures: [list features]\nInclude: TypeScript, state management, accessibility.', category: 'Implementation', tags: ['react', 'frontend'], source: 'React Docs' },
    { promptId: 'impl-04', title: 'Authentication Flow', prompt: 'Implement authentication for [app type] using [method: JWT/OAuth/Session].\nInclude: login, register, password reset, refresh tokens, secure storage.', category: 'Implementation', tags: ['auth', 'security'], source: 'OWASP' },
    { promptId: 'impl-05', title: 'CRUD Operations', prompt: 'Implement CRUD operations for [entity] in [framework].\nDatabase: [type]\nInclude: validation, error handling, pagination, filtering.', category: 'Implementation', tags: ['crud', 'database'], source: 'Clean Architecture' },
    { promptId: 'impl-06', title: 'Form Validation', prompt: 'Create a form validation system for [form type].\nFields: [list fields]\nValidations: required, email, min/max length, custom rules.\nShow inline errors.', category: 'Implementation', tags: ['form', 'validation'], source: 'UX Best Practices' },
    { promptId: 'impl-07', title: 'File Upload Handler', prompt: 'Implement file upload for [file types] with:\n- Size validation (max [size])\n- Type validation\n- Progress tracking\n- Error handling\n- Cloud storage integration', category: 'Implementation', tags: ['upload', 'files'], source: 'AWS S3 Docs' },
    { promptId: 'impl-08', title: 'Pagination Component', prompt: 'Create a pagination component with:\n- Page numbers\n- Next/prev buttons\n- Items per page selector\n- Jump to page\n- Total count display', category: 'Implementation', tags: ['pagination', 'ui'], source: 'Material Design' },
    { promptId: 'impl-09', title: 'Search Functionality', prompt: 'Implement search for [data type] with:\n- Debounced input\n- Autocomplete suggestions\n- Filters\n- Highlighting results\n- Recent searches', category: 'Implementation', tags: ['search', 'filter'], source: 'Algolia Docs' },
    { promptId: 'impl-10', title: 'WebSocket Connection', prompt: 'Implement WebSocket for [feature: chat/notifications/live-updates].\nInclude: reconnection logic, heartbeat, message queuing, error handling.', category: 'Implementation', tags: ['websocket', 'realtime'], source: 'Socket.io Docs' },
    { promptId: 'impl-11', title: 'State Management', prompt: 'Set up state management using [Redux/Zustand/Context] for [app].\nInclude: store structure, actions, selectors, persistence.', category: 'Implementation', tags: ['state', 'redux'], source: 'Redux Toolkit' },
    { promptId: 'impl-12', title: 'Email Service', prompt: 'Implement email service for [use case] using [provider].\nEmails: welcome, verification, password reset, notifications.\nInclude templates.', category: 'Implementation', tags: ['email', 'service'], source: 'SendGrid Docs' },
    { promptId: 'impl-13', title: 'Payment Integration', prompt: 'Integrate [Stripe/PayPal] for [payment type: one-time/subscription].\nInclude: checkout, webhooks, refunds, receipt generation.', category: 'Implementation', tags: ['payment', 'stripe'], source: 'Stripe Docs' },
    { promptId: 'impl-14', title: 'Notification System', prompt: 'Build notification system with:\n- Push notifications\n- In-app notifications\n- Email fallback\n- Preferences management\n- Batch sending', category: 'Implementation', tags: ['notifications'], source: 'Firebase FCM' },
    { promptId: 'impl-15', title: 'Caching Layer', prompt: 'Implement caching for [data type] using [Redis/memory].\nInclude: cache invalidation, TTL, cache-aside pattern, fallback.', category: 'Implementation', tags: ['cache', 'redis'], source: 'Redis Docs' },
    { promptId: 'impl-16', title: 'Rate Limiter', prompt: 'Implement rate limiting for API with:\n- Per-user limits\n- Per-endpoint limits\n- Sliding window\n- Response headers\n- Retry-after', category: 'Implementation', tags: ['rate-limit', 'api'], source: 'API Security' },
    { promptId: 'impl-17', title: 'Image Processing', prompt: 'Implement image processing for [use case]:\n- Resize/crop\n- Format conversion\n- Compression\n- Watermarking\n- Thumbnail generation', category: 'Implementation', tags: ['image', 'media'], source: 'Sharp.js Docs' },
    { promptId: 'impl-18', title: 'Export to PDF/CSV', prompt: 'Implement data export to [PDF/CSV/Excel] for [data type].\nInclude: formatting, styling, pagination, progress indicator.', category: 'Implementation', tags: ['export', 'pdf'], source: 'pdfkit Docs' },
    { promptId: 'impl-19', title: 'Drag and Drop', prompt: 'Implement drag and drop for [use case: file upload/reorder/kanban].\nInclude: visual feedback, touch support, accessibility.', category: 'Implementation', tags: ['dnd', 'ui'], source: 'dnd-kit Docs' },
    { promptId: 'impl-20', title: 'Infinite Scroll', prompt: 'Implement infinite scroll for [data type].\nInclude: intersection observer, loading states, error handling, scroll position restoration.', category: 'Implementation', tags: ['infinite-scroll'], source: 'React Query' },

    // ===== DEBUGGING (20 prompts) =====
    { promptId: 'debug-01', title: 'Bug Analysis', prompt: 'Debug this code:\n[code]\nError: [error message]\nExpected: [behavior]\nActual: [behavior]\nFind root cause and fix.', category: 'Debugging', tags: ['bug', 'fix'], source: 'Debugging Guide' },
    { promptId: 'debug-02', title: 'Performance Issue', prompt: 'My code is slow:\n[code]\nCurrent: [metrics]\nTarget: [goal]\nIdentify bottlenecks and optimize.', category: 'Debugging', tags: ['performance'], source: 'Performance Guide' },
    { promptId: 'debug-03', title: 'Memory Leak', prompt: 'Investigate memory leak in:\n[code/component]\nSymptoms: [describe]\nFind cause and provide fix.', category: 'Debugging', tags: ['memory', 'leak'], source: 'Chrome DevTools' },
    { promptId: 'debug-04', title: 'Race Condition', prompt: 'I have a race condition in:\n[code]\nSymptoms: [inconsistent behavior]\nProvide thread-safe solution.', category: 'Debugging', tags: ['race-condition'], source: 'Concurrency Patterns' },
    { promptId: 'debug-05', title: 'API Error', prompt: 'Debug API error:\nEndpoint: [url]\nStatus: [code]\nResponse: [body]\nRequest: [details]\nFind cause and fix.', category: 'Debugging', tags: ['api', 'error'], source: 'REST Debugging' },
    { promptId: 'debug-06', title: 'TypeScript Error', prompt: 'Fix TypeScript error:\n[code]\nError: [TS error message]\nExplain why it occurs and provide correct types.', category: 'Debugging', tags: ['typescript'], source: 'TS Handbook' },
    { promptId: 'debug-07', title: 'React Re-renders', prompt: 'Component re-renders too often:\n[component code]\nIdentify cause and optimize with useMemo/useCallback.', category: 'Debugging', tags: ['react', 'render'], source: 'React Profiler' },
    { promptId: 'debug-08', title: 'CSS Layout Issue', prompt: 'Fix CSS layout problem:\n[HTML/CSS]\nExpected: [description]\nActual: [description]\nProvide corrected styles.', category: 'Debugging', tags: ['css', 'layout'], source: 'CSS Tricks' },
    { promptId: 'debug-09', title: 'Database Query Slow', prompt: 'Query is slow:\n[SQL query]\nExecution time: [time]\nAnalyze and optimize with indexes/rewrite.', category: 'Debugging', tags: ['sql', 'query'], source: 'Query Optimization' },
    { promptId: 'debug-10', title: 'Authentication Failure', prompt: 'Auth is failing:\nMethod: [JWT/Session/OAuth]\nSymptom: [describe]\nLogs: [relevant logs]\nFind and fix issue.', category: 'Debugging', tags: ['auth', 'security'], source: 'Auth Debugging' },
    { promptId: 'debug-11', title: 'CORS Error', prompt: 'Fix CORS error:\nError: [message]\nFrontend: [origin]\nBackend: [origin]\nProvide correct CORS config.', category: 'Debugging', tags: ['cors', 'api'], source: 'MDN CORS' },
    { promptId: 'debug-12', title: 'WebSocket Disconnect', prompt: 'WebSocket keeps disconnecting:\nSetup: [describe]\nInterval: [how often]\nDiagnose and implement stable connection.', category: 'Debugging', tags: ['websocket'], source: 'WebSocket RFC' },
    { promptId: 'debug-13', title: 'Build Error', prompt: 'Build is failing:\nError: [build error]\nConfig: [relevant config]\nDependencies: [package.json]\nFix the build.', category: 'Debugging', tags: ['build', 'config'], source: 'Webpack/Vite' },
    { promptId: 'debug-14', title: 'Test Flakiness', prompt: 'Test is flaky:\n[test code]\nFails: [pattern]\nMake test reliable and deterministic.', category: 'Debugging', tags: ['testing', 'flaky'], source: 'Jest Best Practices' },
    { promptId: 'debug-15', title: 'State Not Updating', prompt: 'State not updating correctly:\n[component code]\nExpected: [state change]\nActual: [current behavior]\nFix state logic.', category: 'Debugging', tags: ['state', 'react'], source: 'React State' },
    { promptId: 'debug-16', title: 'Environment Variable', prompt: 'Env variable not working:\nVariable: [name]\nUsage: [code]\nConfig: [.env setup]\nDebug and fix.', category: 'Debugging', tags: ['env', 'config'], source: 'dotenv Docs' },
    { promptId: 'debug-17', title: 'Date/Timezone Issue', prompt: 'Date/timezone bug:\n[code]\nExpected: [date/time]\nActual: [date/time]\nFix timezone handling.', category: 'Debugging', tags: ['date', 'timezone'], source: 'Moment/date-fns' },
    { promptId: 'debug-18', title: 'File Path Error', prompt: 'File path issue:\nError: [ENOENT/path error]\nCode: [relevant code]\nOS: [Windows/Mac/Linux]\nFix path handling.', category: 'Debugging', tags: ['file', 'path'], source: 'Node.js Path' },
    { promptId: 'debug-19', title: 'Async/Await Issue', prompt: 'Async code not working:\n[code]\nProblem: [describe]\nFix async/await/Promise handling.', category: 'Debugging', tags: ['async', 'promise'], source: 'JS Async Guide' },
    { promptId: 'debug-20', title: 'Third-Party Integration', prompt: 'Integration failing:\nService: [name]\nError: [message]\nCode: [integration code]\nDebug and fix.', category: 'Debugging', tags: ['integration'], source: 'API Docs' },

    // ===== REFACTORING (15 prompts) =====
    { promptId: 'refactor-01', title: 'Code Quality', prompt: 'Refactor for quality:\n[code]\nGoals: readability, SOLID, reduce complexity, add types.\nKeep functionality, explain changes.', category: 'Refactoring', tags: ['clean-code'], source: 'Clean Code' },
    { promptId: 'refactor-02', title: 'To TypeScript', prompt: 'Convert to TypeScript:\n[JS code]\nAdd types, interfaces, generics, null handling.\nMaintain functionality.', category: 'Refactoring', tags: ['typescript'], source: 'TS Migration' },
    { promptId: 'refactor-03', title: 'Extract Function', prompt: 'Extract reusable functions from:\n[code]\nIdentify repeated logic, create pure functions, add types.', category: 'Refactoring', tags: ['function'], source: 'Clean Code' },
    { promptId: 'refactor-04', title: 'Design Pattern', prompt: 'Apply [pattern: Factory/Strategy/Observer] to:\n[code]\nExplain why this pattern fits.', category: 'Refactoring', tags: ['patterns'], source: 'Design Patterns' },
    { promptId: 'refactor-05', title: 'Class to Hooks', prompt: 'Convert React class to functional:\n[class component]\nUse hooks: useState, useEffect, useCallback.', category: 'Refactoring', tags: ['react', 'hooks'], source: 'React Hooks' },
    { promptId: 'refactor-06', title: 'Reduce Complexity', prompt: 'Reduce cyclomatic complexity:\n[code]\nSimplify conditionals, use early returns, extract.', category: 'Refactoring', tags: ['complexity'], source: 'Code Metrics' },
    { promptId: 'refactor-07', title: 'DRY Principle', prompt: 'Remove duplication from:\n[code]\nApply DRY, create shared utilities.', category: 'Refactoring', tags: ['dry'], source: 'Clean Code' },
    { promptId: 'refactor-08', title: 'Error Handling', prompt: 'Improve error handling:\n[code]\nAdd try-catch, custom errors, user messages.', category: 'Refactoring', tags: ['errors'], source: 'Error Handling' },
    { promptId: 'refactor-09', title: 'API Versioning', prompt: 'Add versioning to API:\n[current routes]\nStrategy: URL/header versioning.\nMigration path.', category: 'Refactoring', tags: ['api', 'version'], source: 'API Design' },
    { promptId: 'refactor-10', title: 'Modularize Code', prompt: 'Break monolith into modules:\n[large file]\nCreate logical separation, clear interfaces.', category: 'Refactoring', tags: ['modules'], source: 'Architecture' },
    { promptId: 'refactor-11', title: 'Async Refactor', prompt: 'Refactor callbacks to async/await:\n[callback code]\nHandle errors properly.', category: 'Refactoring', tags: ['async'], source: 'JS Async' },
    { promptId: 'refactor-12', title: 'Component Split', prompt: 'Split large component:\n[component]\nCreate smaller, focused components.', category: 'Refactoring', tags: ['react'], source: 'React Patterns' },
    { promptId: 'refactor-13', title: 'Dependency Injection', prompt: 'Apply DI to:\n[code]\nRemove hard dependencies, improve testability.', category: 'Refactoring', tags: ['di', 'solid'], source: 'SOLID' },
    { promptId: 'refactor-14', title: 'Naming Conventions', prompt: 'Improve naming in:\n[code]\nUse descriptive, consistent naming.', category: 'Refactoring', tags: ['naming'], source: 'Clean Code' },
    { promptId: 'refactor-15', title: 'Magic Numbers', prompt: 'Replace magic values:\n[code]\nUse named constants, enums.', category: 'Refactoring', tags: ['constants'], source: 'Clean Code' },

    // ===== TESTING (15 prompts) =====
    { promptId: 'test-01', title: 'Unit Tests', prompt: 'Write unit tests for:\n[code]\nFramework: [Jest/Vitest]\nCover: happy path, edge cases, errors.', category: 'Testing', tags: ['unit-test'], source: 'Jest Docs' },
    { promptId: 'test-02', title: 'Integration Tests', prompt: 'Write integration tests for [feature].\nStack: [describe]\nTest API endpoints, DB operations.', category: 'Testing', tags: ['integration'], source: 'Testing Library' },
    { promptId: 'test-03', title: 'E2E Tests', prompt: 'Write E2E tests for [flow] using [Playwright/Cypress].\nCover: user journey, error states.', category: 'Testing', tags: ['e2e', 'cypress'], source: 'Cypress Docs' },
    { promptId: 'test-04', title: 'Component Tests', prompt: 'Test React component:\n[component]\nTest: render, props, events, states.', category: 'Testing', tags: ['react', 'component'], source: 'Testing Library' },
    { promptId: 'test-05', title: 'API Tests', prompt: 'Write API tests for:\n[endpoint]\nTest: responses, validation, auth, errors.', category: 'Testing', tags: ['api', 'test'], source: 'Supertest Docs' },
    { promptId: 'test-06', title: 'Mock Dependencies', prompt: 'Mock external dependencies for:\n[code with deps]\nCreate mocks for API/DB/services.', category: 'Testing', tags: ['mock'], source: 'Jest Mocking' },
    { promptId: 'test-07', title: 'Test Coverage', prompt: 'Improve test coverage for:\n[code/module]\nCurrent: [%]\nIdentify untested paths.', category: 'Testing', tags: ['coverage'], source: 'Istanbul' },
    { promptId: 'test-08', title: 'Snapshot Tests', prompt: 'Add snapshot tests for:\n[UI component]\nCapture render output, detect changes.', category: 'Testing', tags: ['snapshot'], source: 'Jest Snapshots' },
    { promptId: 'test-09', title: 'TDD Implementation', prompt: 'Implement [feature] using TDD.\nWrite tests first, then implementation.', category: 'Testing', tags: ['tdd'], source: 'TDD by Example' },
    { promptId: 'test-10', title: 'Load Testing', prompt: 'Create load test for [endpoint/app].\nTargets: [requests/sec], [response time].', category: 'Testing', tags: ['load', 'performance'], source: 'k6 Docs' },
    { promptId: 'test-11', title: 'Security Tests', prompt: 'Write security tests checking:\n- SQL injection\n- XSS\n- Auth bypass\n- Input validation', category: 'Testing', tags: ['security'], source: 'OWASP Testing' },
    { promptId: 'test-12', title: 'Test Fixtures', prompt: 'Create test fixtures for:\n[data model]\nInclude factories, seed data.', category: 'Testing', tags: ['fixtures'], source: 'Factory Pattern' },
    { promptId: 'test-13', title: 'Async Tests', prompt: 'Write async tests for:\n[async code]\nHandle promises, timeouts properly.', category: 'Testing', tags: ['async'], source: 'Jest Async' },
    { promptId: 'test-14', title: 'Visual Regression', prompt: 'Set up visual regression for [component/page].\nCapture screenshots, compare changes.', category: 'Testing', tags: ['visual'], source: 'Percy/Chromatic' },
    { promptId: 'test-15', title: 'Accessibility Tests', prompt: 'Write a11y tests for:\n[component]\nCheck: ARIA, keyboard nav, screen reader.', category: 'Testing', tags: ['a11y'], source: 'axe-core' },

    // ===== DOCUMENTATION (10 prompts) =====
    { promptId: 'docs-01', title: 'Code Comments', prompt: 'Add JSDoc/TSDoc to:\n[code]\nInclude params, returns, examples.', category: 'Documentation', tags: ['jsdoc'], source: 'TSDoc' },
    { promptId: 'docs-02', title: 'README', prompt: 'Create README for [project]:\nOverview, install, usage, config, API, contributing.', category: 'Documentation', tags: ['readme'], source: 'README Template' },
    { promptId: 'docs-03', title: 'API Documentation', prompt: 'Document API:\n[endpoints]\nInclude: methods, params, responses, examples.', category: 'Documentation', tags: ['api'], source: 'OpenAPI/Swagger' },
    { promptId: 'docs-04', title: 'Architecture Doc', prompt: 'Document architecture for [system]:\nDiagrams, components, data flow, decisions.', category: 'Documentation', tags: ['architecture'], source: 'Arc42' },
    { promptId: 'docs-05', title: 'Changelog', prompt: 'Create CHANGELOG for [version]:\nAdded, changed, deprecated, removed, fixed.', category: 'Documentation', tags: ['changelog'], source: 'Keep a Changelog' },
    { promptId: 'docs-06', title: 'Contributing Guide', prompt: 'Write CONTRIBUTING.md:\nSetup, code style, PR process, testing.', category: 'Documentation', tags: ['contribute'], source: 'Open Source Guide' },
    { promptId: 'docs-07', title: 'Environment Setup', prompt: 'Document dev environment setup:\nPrerequisites, installation, configuration.', category: 'Documentation', tags: ['setup'], source: 'Dev Docs' },
    { promptId: 'docs-08', title: 'Deployment Guide', prompt: 'Document deployment process:\nEnvironments, CI/CD, rollback, monitoring.', category: 'Documentation', tags: ['deploy'], source: 'DevOps Guide' },
    { promptId: 'docs-09', title: 'Error Codes', prompt: 'Document error codes for [system]:\nCode, message, cause, resolution.', category: 'Documentation', tags: ['errors'], source: 'Error Handling' },
    { promptId: 'docs-10', title: 'Troubleshooting', prompt: 'Create troubleshooting guide:\nCommon issues, symptoms, solutions.', category: 'Documentation', tags: ['troubleshoot'], source: 'Support Docs' },

    // ===== SECURITY (15 prompts) =====
    { promptId: 'sec-01', title: 'Security Review', prompt: 'Review for security:\n[code]\nCheck: injection, XSS, auth, data exposure.', category: 'Security', tags: ['review'], source: 'OWASP' },
    { promptId: 'sec-02', title: 'Input Validation', prompt: 'Add validation for:\n[input handling code]\nSanitize, validate, escape user input.', category: 'Security', tags: ['validation'], source: 'OWASP' },
    { promptId: 'sec-03', title: 'Auth Implementation', prompt: 'Secure auth implementation:\n[auth code]\nVerify: password hashing, session, tokens.', category: 'Security', tags: ['auth'], source: 'OWASP Auth' },
    { promptId: 'sec-04', title: 'SQL Injection', prompt: 'Fix SQL injection in:\n[query code]\nUse parameterized queries/ORM.', category: 'Security', tags: ['sql', 'injection'], source: 'OWASP SQL' },
    { promptId: 'sec-05', title: 'XSS Prevention', prompt: 'Fix XSS vulnerabilities:\n[code with user content]\nSanitize output, use CSP.', category: 'Security', tags: ['xss'], source: 'OWASP XSS' },
    { promptId: 'sec-06', title: 'CSRF Protection', prompt: 'Add CSRF protection:\n[form/api code]\nImplement tokens, SameSite cookies.', category: 'Security', tags: ['csrf'], source: 'OWASP CSRF' },
    { promptId: 'sec-07', title: 'Secret Management', prompt: 'Improve secret handling:\n[code with secrets]\nUse env vars, vault, no hardcoding.', category: 'Security', tags: ['secrets'], source: 'Security Best Practices' },
    { promptId: 'sec-08', title: 'Encryption', prompt: 'Add encryption for [data type]:\nAt rest, in transit, key management.', category: 'Security', tags: ['encryption'], source: 'Crypto Best Practices' },
    { promptId: 'sec-09', title: 'Access Control', prompt: 'Implement RBAC for:\n[resource]\nRoles, permissions, middleware.', category: 'Security', tags: ['rbac', 'auth'], source: 'OWASP Access' },
    { promptId: 'sec-10', title: 'Security Headers', prompt: 'Add security headers:\nCSP, HSTS, X-Frame-Options, X-Content-Type.', category: 'Security', tags: ['headers'], source: 'OWASP Headers' },
    { promptId: 'sec-11', title: 'Rate Limiting', prompt: 'Implement rate limiting:\n[api]\nPer-user, per-IP, response headers.', category: 'Security', tags: ['rate-limit'], source: 'API Security' },
    { promptId: 'sec-12', title: 'Audit Logging', prompt: 'Add audit logging for:\n[actions]\nLog: who, what, when, where.', category: 'Security', tags: ['audit', 'logging'], source: 'Security Logging' },
    { promptId: 'sec-13', title: 'Dependencies Audit', prompt: 'Audit dependencies in:\n[package.json]\nFind vulnerabilities, update safe versions.', category: 'Security', tags: ['dependencies'], source: 'npm audit' },
    { promptId: 'sec-14', title: 'File Upload Security', prompt: 'Secure file uploads:\n[upload code]\nValidate type, size, scan, store safely.', category: 'Security', tags: ['upload'], source: 'OWASP Upload' },
    { promptId: 'sec-15', title: 'API Security', prompt: 'Secure API endpoints:\n[routes]\nAuth, validation, rate limits, logging.', category: 'Security', tags: ['api'], source: 'API Security' },

    // ===== DATABASE (15 prompts) =====
    { promptId: 'db-01', title: 'Query Optimization', prompt: 'Optimize query:\n[SQL]\nCurrent time: [ms]\nAnalyze, add indexes, rewrite.', category: 'Database', tags: ['sql', 'optimize'], source: 'SQL Performance' },
    { promptId: 'db-02', title: 'Schema Design', prompt: 'Design schema for [app]:\nEntities: [list]\nRelationships, indexes, constraints.', category: 'Database', tags: ['schema'], source: 'Database Design' },
    { promptId: 'db-03', title: 'Migration Script', prompt: 'Create migration for:\n[schema change]\nUp and down migrations, data handling.', category: 'Database', tags: ['migration'], source: 'Migrations Guide' },
    { promptId: 'db-04', title: 'Index Strategy', prompt: 'Plan indexes for:\n[table/queries]\nBalances reads vs writes.', category: 'Database', tags: ['index'], source: 'Indexing Guide' },
    { promptId: 'db-05', title: 'N+1 Problem', prompt: 'Fix N+1 query issue:\n[code]\nUse eager loading, joins.', category: 'Database', tags: ['n+1', 'orm'], source: 'ORM Best Practices' },
    { promptId: 'db-06', title: 'Transaction Handling', prompt: 'Add transactions to:\n[code]\nACID compliance, rollback handling.', category: 'Database', tags: ['transaction'], source: 'ACID' },
    { promptId: 'db-07', title: 'Soft Delete', prompt: 'Implement soft delete for:\n[entity]\nDeleted_at, queries, cascading.', category: 'Database', tags: ['soft-delete'], source: 'Data Patterns' },
    { promptId: 'db-08', title: 'Data Seeding', prompt: 'Create seed data for:\n[tables]\nDev, test, demo data.', category: 'Database', tags: ['seed'], source: 'Seeding Guide' },
    { promptId: 'db-09', title: 'Full-Text Search', prompt: 'Add full-text search:\nDB: [type]\nFields: [columns]\nRanking, highlighting.', category: 'Database', tags: ['search'], source: 'FTS Guide' },
    { promptId: 'db-10', title: 'Connection Pooling', prompt: 'Configure connection pool:\n[setup]\nMin/max connections, timeouts.', category: 'Database', tags: ['pool'], source: 'DB Connections' },
    { promptId: 'db-11', title: 'Backup Strategy', prompt: 'Design backup strategy:\nDB: [type]\nFrequency, retention, restoration.', category: 'Database', tags: ['backup'], source: 'DBA Guide' },
    { promptId: 'db-12', title: 'Partitioning', prompt: 'Partition table:\n[table details]\nStrategy: range/hash/list.', category: 'Database', tags: ['partition'], source: 'Partitioning' },
    { promptId: 'db-13', title: 'NoSQL Model', prompt: 'Design NoSQL schema for:\n[app]\nDocument structure, denormalization.', category: 'Database', tags: ['nosql', 'mongodb'], source: 'MongoDB Patterns' },
    { promptId: 'db-14', title: 'Query Builder', prompt: 'Build dynamic query for:\n[filters]\nSafe, typed query construction.', category: 'Database', tags: ['query'], source: 'Query Builders' },
    { promptId: 'db-15', title: 'Audit Trail', prompt: 'Add audit trail to:\n[entity]\nTrack changes, who/when/what.', category: 'Database', tags: ['audit'], source: 'Audit Pattern' },

    // ===== ALGORITHMS (15 prompts) =====
    { promptId: 'algo-01', title: 'Algorithm Design', prompt: 'Implement algorithm for:\n[problem]\nInput/Output format, complexity targets.', category: 'Algorithms', tags: ['algorithm'], source: 'CLRS' },
    { promptId: 'algo-02', title: 'Data Structure', prompt: 'Implement [structure] in TypeScript:\nOperations, types, complexity.', category: 'Algorithms', tags: ['data-structure'], source: 'DS Guide' },
    { promptId: 'algo-03', title: 'Sorting', prompt: 'Implement [sort algorithm]:\nStable, in-place options, complexity.', category: 'Algorithms', tags: ['sort'], source: 'Algorithms' },
    { promptId: 'algo-04', title: 'Search Algorithm', prompt: 'Implement [search: binary/DFS/BFS]:\nInput format, efficiency.', category: 'Algorithms', tags: ['search'], source: 'Algorithms' },
    { promptId: 'algo-05', title: 'Tree Operations', prompt: 'Implement tree operations:\nTraversals, insert, delete, balance.', category: 'Algorithms', tags: ['tree'], source: 'Trees' },
    { promptId: 'algo-06', title: 'Graph Algorithm', prompt: 'Implement [graph algo]:\nShortest path, connectivity, cycles.', category: 'Algorithms', tags: ['graph'], source: 'Graph Theory' },
    { promptId: 'algo-07', title: 'Dynamic Programming', prompt: 'Solve with DP:\n[problem]\nRecurrence, memoization, tabulation.', category: 'Algorithms', tags: ['dp'], source: 'DP Patterns' },
    { promptId: 'algo-08', title: 'String Algorithm', prompt: 'Implement string algorithm:\n[pattern matching/parsing/manipulation]', category: 'Algorithms', tags: ['string'], source: 'String Algorithms' },
    { promptId: 'algo-09', title: 'Hash Table', prompt: 'Implement hash table:\nCollision handling, resize, efficiency.', category: 'Algorithms', tags: ['hash'], source: 'Hashing' },
    { promptId: 'algo-10', title: 'Heap/Priority Queue', prompt: 'Implement priority queue:\nInsert, extract, heapify.', category: 'Algorithms', tags: ['heap'], source: 'Heaps' },
    { promptId: 'algo-11', title: 'Recursion', prompt: 'Convert to recursion or iteration:\n[code]\nStack optimization, tail recursion.', category: 'Algorithms', tags: ['recursion'], source: 'Recursion' },
    { promptId: 'algo-12', title: 'Bit Manipulation', prompt: 'Solve using bit ops:\n[problem]\nEfficient bitwise solution.', category: 'Algorithms', tags: ['bits'], source: 'Bit Manipulation' },
    { promptId: 'algo-13', title: 'Two Pointers', prompt: 'Solve with two pointers:\n[problem]\nIn-place, O(n) solution.', category: 'Algorithms', tags: ['pointers'], source: 'Two Pointers' },
    { promptId: 'algo-14', title: 'Sliding Window', prompt: 'Apply sliding window:\n[problem]\nFixed/variable window.', category: 'Algorithms', tags: ['window'], source: 'Sliding Window' },
    { promptId: 'algo-15', title: 'Complexity Analysis', prompt: 'Analyze complexity:\n[algorithm]\nTime, space, best/worst/average.', category: 'Algorithms', tags: ['complexity'], source: 'Big O' },

    // ===== ARCHITECTURE (15 prompts) =====
    { promptId: 'arch-01', title: 'System Design', prompt: 'Design system for [app]:\nScale: [users]\nComponents, data flow, trade-offs.', category: 'Architecture', tags: ['system'], source: 'System Design' },
    { promptId: 'arch-02', title: 'Microservices', prompt: 'Design microservices for [domain]:\nService boundaries, communication.', category: 'Architecture', tags: ['microservices'], source: 'Microservices' },
    { promptId: 'arch-03', title: 'API Gateway', prompt: 'Design API gateway:\nRouting, auth, rate limiting, logging.', category: 'Architecture', tags: ['gateway'], source: 'API Gateway' },
    { promptId: 'arch-04', title: 'Event-Driven', prompt: 'Design event-driven system:\nEvents, producers, consumers, ordering.', category: 'Architecture', tags: ['events'], source: 'Event Sourcing' },
    { promptId: 'arch-05', title: 'CQRS Pattern', prompt: 'Apply CQRS to [domain]:\nCommand/query separation, sync.', category: 'Architecture', tags: ['cqrs'], source: 'CQRS' },
    { promptId: 'arch-06', title: 'Message Queue', prompt: 'Design message queue system:\n[RabbitMQ/Kafka]\nTopics, consumers, retry.', category: 'Architecture', tags: ['queue'], source: 'Message Queues' },
    { promptId: 'arch-07', title: 'Load Balancing', prompt: 'Design load balancing:\nStrategies, health checks, sticky.', category: 'Architecture', tags: ['load-balancer'], source: 'Load Balancing' },
    { promptId: 'arch-08', title: 'Caching Strategy', prompt: 'Design caching for [system]:\nLayers, invalidation, consistency.', category: 'Architecture', tags: ['cache'], source: 'Caching Patterns' },
    { promptId: 'arch-09', title: 'Database Sharding', prompt: 'Design sharding strategy:\nShard key, routing, rebalancing.', category: 'Architecture', tags: ['sharding'], source: 'DB Sharding' },
    { promptId: 'arch-10', title: 'Disaster Recovery', prompt: 'Design DR plan:\nRPO/RTO, backup, failover.', category: 'Architecture', tags: ['dr'], source: 'DR Planning' },
    { promptId: 'arch-11', title: 'Monolith to Micro', prompt: 'Plan migration from monolith:\nStrangle fig, domain extraction.', category: 'Architecture', tags: ['migration'], source: 'Refactoring' },
    { promptId: 'arch-12', title: 'Serverless Design', prompt: 'Design serverless for [use case]:\nFunctions, triggers, cold start.', category: 'Architecture', tags: ['serverless'], source: 'Serverless' },
    { promptId: 'arch-13', title: 'Clean Architecture', prompt: 'Apply clean architecture:\nLayers, dependencies, domain.', category: 'Architecture', tags: ['clean'], source: 'Clean Architecture' },
    { promptId: 'arch-14', title: 'Hexagonal', prompt: 'Apply hexagonal architecture:\nPorts, adapters, core.', category: 'Architecture', tags: ['hexagonal'], source: 'Hexagonal' },
    { promptId: 'arch-15', title: 'Feature Flags', prompt: 'Design feature flags system:\nToggle management, rollout.', category: 'Architecture', tags: ['flags'], source: 'Feature Flags' },

    // ===== DEVOPS (15 prompts) =====
    { promptId: 'devops-01', title: 'CI/CD Pipeline', prompt: 'Create CI/CD for [app]:\n[GitHub Actions/GitLab CI]\nBuild, test, deploy stages.', category: 'DevOps', tags: ['ci', 'cd'], source: 'GitHub Actions' },
    { promptId: 'devops-02', title: 'Docker Setup', prompt: 'Create Dockerfile for [app]:\nMulti-stage, optimization, security.', category: 'DevOps', tags: ['docker'], source: 'Docker Docs' },
    { promptId: 'devops-03', title: 'Kubernetes Config', prompt: 'Create K8s manifests for [app]:\nDeployment, service, ingress, config.', category: 'DevOps', tags: ['k8s'], source: 'Kubernetes' },
    { promptId: 'devops-04', title: 'Infrastructure as Code', prompt: 'Write Terraform for [infra]:\nProvider setup, resources, state.', category: 'DevOps', tags: ['terraform'], source: 'Terraform' },
    { promptId: 'devops-05', title: 'Monitoring Setup', prompt: 'Set up monitoring:\nMetrics, alerts, dashboards.', category: 'DevOps', tags: ['monitoring'], source: 'Prometheus/Grafana' },
    { promptId: 'devops-06', title: 'Logging System', prompt: 'Set up centralized logging:\nCollection, aggregation, search.', category: 'DevOps', tags: ['logging'], source: 'ELK Stack' },
    { promptId: 'devops-07', title: 'Auto Scaling', prompt: 'Configure auto scaling:\nMetrics, thresholds, cooldown.', category: 'DevOps', tags: ['scaling'], source: 'Auto Scaling' },
    { promptId: 'devops-08', title: 'Secret Management', prompt: 'Set up secrets management:\n[Vault/AWS Secrets]\nRotation, access.', category: 'DevOps', tags: ['secrets'], source: 'HashiCorp Vault' },
    { promptId: 'devops-09', title: 'Blue-Green Deploy', prompt: 'Set up blue-green deployment:\nSwitch mechanism, rollback.', category: 'DevOps', tags: ['deploy'], source: 'Deployment Patterns' },
    { promptId: 'devops-10', title: 'Container Registry', prompt: 'Set up container registry:\nImage management, scanning.', category: 'DevOps', tags: ['registry'], source: 'Container Registry' },
    { promptId: 'devops-11', title: 'Health Checks', prompt: 'Implement health checks:\nLiveness, readiness, startup.', category: 'DevOps', tags: ['health'], source: 'K8s Probes' },
    { promptId: 'devops-12', title: 'Nginx Config', prompt: 'Configure Nginx for [use case]:\nReverse proxy, SSL, caching.', category: 'DevOps', tags: ['nginx'], source: 'Nginx Docs' },
    { promptId: 'devops-13', title: 'SSL/TLS Setup', prompt: 'Set up SSL/TLS:\nCertificates, renewal, hardening.', category: 'DevOps', tags: ['ssl'], source: 'SSL Best Practices' },
    { promptId: 'devops-14', title: 'Environment Config', prompt: 'Set up environment config:\nDev, staging, prod segregation.', category: 'DevOps', tags: ['env'], source: '12-Factor App' },
    { promptId: 'devops-15', title: 'Backup Automation', prompt: 'Automate backups:\nSchedule, retention, verification.', category: 'DevOps', tags: ['backup'], source: 'Backup Strategies' },

    // ===== FRONTEND (15 prompts) =====
    { promptId: 'fe-01', title: 'Responsive Design', prompt: 'Make responsive:\n[component/page]\nBreakpoints, mobile-first.', category: 'Frontend', tags: ['responsive'], source: 'CSS Grid/Flex' },
    { promptId: 'fe-02', title: 'Accessibility', prompt: 'Improve accessibility:\n[component]\nARIA, keyboard, screen reader.', category: 'Frontend', tags: ['a11y'], source: 'WCAG' },
    { promptId: 'fe-03', title: 'Animation', prompt: 'Add animations to [element]:\nCSS/Framer Motion, performance.', category: 'Frontend', tags: ['animation'], source: 'Framer Motion' },
    { promptId: 'fe-04', title: 'Form UX', prompt: 'Improve form UX:\n[form]\nValidation, feedback, autofill.', category: 'Frontend', tags: ['form', 'ux'], source: 'Form UX' },
    { promptId: 'fe-05', title: 'Data Fetching', prompt: 'Implement data fetching:\n[React Query/SWR]\nCaching, refetch, error handling.', category: 'Frontend', tags: ['fetch'], source: 'React Query' },
    { promptId: 'fe-06', title: 'Dark Mode', prompt: 'Implement dark mode:\nTheme switching, system preference.', category: 'Frontend', tags: ['theme'], source: 'Theme Guide' },
    { promptId: 'fe-07', title: 'Image Optimization', prompt: 'Optimize images:\nLazy loading, formats, responsive.', category: 'Frontend', tags: ['images'], source: 'Next/Image' },
    { promptId: 'fe-08', title: 'SEO', prompt: 'Improve SEO for:\n[page]\nMeta tags, structured data, performance.', category: 'Frontend', tags: ['seo'], source: 'SEO Guide' },
    { promptId: 'fe-09', title: 'Bundle Optimization', prompt: 'Optimize bundle size:\nCode splitting, tree shaking, lazy.', category: 'Frontend', tags: ['bundle'], source: 'Webpack/Vite' },
    { promptId: 'fe-10', title: 'PWA Setup', prompt: 'Convert to PWA:\nService worker, manifest, offline.', category: 'Frontend', tags: ['pwa'], source: 'PWA Guide' },
    { promptId: 'fe-11', title: 'Error Boundary', prompt: 'Add error boundaries:\n[app section]\nFallback UI, error reporting.', category: 'Frontend', tags: ['error'], source: 'React Errors' },
    { promptId: 'fe-12', title: 'Virtualization', prompt: 'Add virtualization for [long list]:\nreact-window/virtual.', category: 'Frontend', tags: ['virtual'], source: 'React Virtual' },
    { promptId: 'fe-13', title: 'Internationalization', prompt: 'Add i18n support:\nTranslations, formatting, RTL.', category: 'Frontend', tags: ['i18n'], source: 'i18next' },
    { promptId: 'fe-14', title: 'Skeleton Loading', prompt: 'Add skeleton loaders:\n[components]\nSmooth loading states.', category: 'Frontend', tags: ['skeleton'], source: 'Loading UX' },
    { promptId: 'fe-15', title: 'Toast Notifications', prompt: 'Implement toast system:\nTypes, positioning, queue.', category: 'Frontend', tags: ['toast'], source: 'Toast Library' },

    // ===== PERFORMANCE (15 prompts) =====
    { promptId: 'perf-01', title: 'Profile Code', prompt: 'Profile performance:\n[code/component]\nIdentify bottlenecks.', category: 'Performance', tags: ['profile'], source: 'Chrome DevTools' },
    { promptId: 'perf-02', title: 'React Memoization', prompt: 'Add memoization:\n[component]\nuseMemo, useCallback, React.memo.', category: 'Performance', tags: ['memo', 'react'], source: 'React Performance' },
    { promptId: 'perf-03', title: 'Lazy Loading', prompt: 'Implement lazy loading:\n[resources]\nCode, images, components.', category: 'Performance', tags: ['lazy'], source: 'Lazy Loading' },
    { promptId: 'perf-04', title: 'Database Indexing', prompt: 'Optimize with indexes:\n[queries]\nAnalyze, create, measure.', category: 'Performance', tags: ['index'], source: 'DB Performance' },
    { promptId: 'perf-05', title: 'API Response Time', prompt: 'Optimize API response:\n[endpoint]\nCaching, query, serialization.', category: 'Performance', tags: ['api'], source: 'API Performance' },
    { promptId: 'perf-06', title: 'Memory Optimization', prompt: 'Reduce memory usage:\n[code]\nLeaks, pooling, GC.', category: 'Performance', tags: ['memory'], source: 'Memory Management' },
    { promptId: 'perf-07', title: 'Core Web Vitals', prompt: 'Improve Core Web Vitals:\nLCP, FID, CLS optimization.', category: 'Performance', tags: ['vitals'], source: 'Web Vitals' },
    { promptId: 'perf-08', title: 'Async Operations', prompt: 'Optimize async code:\n[code]\nParallel, batching, streaming.', category: 'Performance', tags: ['async'], source: 'Async Patterns' },
    { promptId: 'perf-09', title: 'Network Optimization', prompt: 'Reduce network usage:\nCompression, CDN, prefetch.', category: 'Performance', tags: ['network'], source: 'Network Performance' },
    { promptId: 'perf-10', title: 'Render Performance', prompt: 'Optimize rendering:\n[UI code]\nLayout thrashing, repaints.', category: 'Performance', tags: ['render'], source: 'Render Performance' },
    { promptId: 'perf-11', title: 'Worker Threads', prompt: 'Offload to worker:\n[heavy computation]\nWeb Worker/Node Worker.', category: 'Performance', tags: ['worker'], source: 'Web Workers' },
    { promptId: 'perf-12', title: 'Streaming', prompt: 'Add streaming:\n[data transfer]\nChunked, SSE, WebSocket.', category: 'Performance', tags: ['stream'], source: 'Streaming' },
    { promptId: 'perf-13', title: 'Debounce/Throttle', prompt: 'Add debounce/throttle:\n[event handlers]\nOptimize event handling.', category: 'Performance', tags: ['debounce'], source: 'Lodash' },
    { promptId: 'perf-14', title: 'Font Optimization', prompt: 'Optimize fonts:\nSubsetting, preload, swap.', category: 'Performance', tags: ['fonts'], source: 'Font Best Practices' },
    { promptId: 'perf-15', title: 'Resource Hints', prompt: 'Add resource hints:\nPreconnect, prefetch, preload.', category: 'Performance', tags: ['hints'], source: 'Resource Hints' },

    // ===== AI/ML (10 prompts) =====
    { promptId: 'ai-01', title: 'AI Integration', prompt: 'Integrate AI for [use case]:\nAPI choice, prompting, error handling.', category: 'AI/ML', tags: ['ai'], source: 'OpenAI Docs' },
    { promptId: 'ai-02', title: 'Prompt Engineering', prompt: 'Design prompts for [task]:\nSystem, user, few-shot examples.', category: 'AI/ML', tags: ['prompt'], source: 'Prompt Engineering' },
    { promptId: 'ai-03', title: 'Streaming Response', prompt: 'Implement streaming AI:\nSSE, token handling, UI updates.', category: 'AI/ML', tags: ['stream', 'ai'], source: 'AI Streaming' },
    { promptId: 'ai-04', title: 'RAG System', prompt: 'Build RAG for [data]:\nEmbeddings, vector DB, retrieval.', category: 'AI/ML', tags: ['rag'], source: 'RAG Patterns' },
    { promptId: 'ai-05', title: 'Function Calling', prompt: 'Implement function calling:\nSchema, execution, response.', category: 'AI/ML', tags: ['function'], source: 'OpenAI Functions' },
    { promptId: 'ai-06', title: 'Chat Memory', prompt: 'Add conversation memory:\nContext window, summarization.', category: 'AI/ML', tags: ['memory', 'chat'], source: 'LangChain' },
    { promptId: 'ai-07', title: 'AI Error Handling', prompt: 'Handle AI errors:\nRetry, fallback, rate limits.', category: 'AI/ML', tags: ['error', 'ai'], source: 'AI Best Practices' },
    { promptId: 'ai-08', title: 'Cost Optimization', prompt: 'Optimize AI costs:\nToken counting, caching, model choice.', category: 'AI/ML', tags: ['cost', 'ai'], source: 'AI Cost Management' },
    { promptId: 'ai-09', title: 'Embeddings', prompt: 'Generate embeddings for [data]:\nModel choice, storage, similarity.', category: 'AI/ML', tags: ['embeddings'], source: 'Embeddings Guide' },
    { promptId: 'ai-10', title: 'AI Safety', prompt: 'Add AI safety measures:\nContent filtering, moderation.', category: 'AI/ML', tags: ['safety', 'ai'], source: 'AI Safety' },

    // ===== CODE REVIEW (10 prompts) =====
    { promptId: 'review-01', title: 'Code Review', prompt: 'Review this code:\n[code]\nCheck: quality, bugs, improvements.', category: 'Code Review', tags: ['review'], source: 'Code Review' },
    { promptId: 'review-02', title: 'PR Review', prompt: 'Review this PR:\nChanges: [description]\nCheck: correctness, style, tests.', category: 'Code Review', tags: ['pr'], source: 'PR Guidelines' },
    { promptId: 'review-03', title: 'Architecture Review', prompt: 'Review architecture:\n[design]\nScalability, maintainability.', category: 'Code Review', tags: ['architecture'], source: 'Architecture Review' },
    { promptId: 'review-04', title: 'Security Review', prompt: 'Security review:\n[code]\nVulnerabilities, best practices.', category: 'Code Review', tags: ['security'], source: 'Security Review' },
    { promptId: 'review-05', title: 'Performance Review', prompt: 'Performance review:\n[code]\nBottlenecks, optimizations.', category: 'Code Review', tags: ['performance'], source: 'Performance Review' },
    { promptId: 'review-06', title: 'API Review', prompt: 'Review API design:\n[endpoints]\nRESTful, consistency, docs.', category: 'Code Review', tags: ['api'], source: 'API Review' },
    { promptId: 'review-07', title: 'Test Review', prompt: 'Review tests:\n[test code]\nCoverage, reliability, clarity.', category: 'Code Review', tags: ['testing'], source: 'Test Review' },
    { promptId: 'review-08', title: 'Schema Review', prompt: 'Review DB schema:\n[schema]\nNormalization, indexes.', category: 'Code Review', tags: ['database'], source: 'Schema Review' },
    { promptId: 'review-09', title: 'Dependency Review', prompt: 'Review dependencies:\n[package.json]\nNecessity, security.', category: 'Code Review', tags: ['deps'], source: 'Dep Review' },
    { promptId: 'review-10', title: 'Accessibility Review', prompt: 'Review accessibility:\n[UI code]\nWCAG compliance.', category: 'Code Review', tags: ['a11y'], source: 'A11y Review' },
];

export default EXTENDED_PROMPTS;
